# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmparametros.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmparametros(object):
    def setupUi(self, frmparametros):
        frmparametros.setObjectName("frmparametros")
        frmparametros.resize(742, 272)
        self.groupBox = QtWidgets.QGroupBox(frmparametros)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 721, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.btnconta = QtWidgets.QPushButton(self.groupBox)
        self.btnconta.setGeometry(QtCore.QRect(500, 20, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnconta.setFont(font)
        self.btnconta.setObjectName("btnconta")
        self.btnbanco = QtWidgets.QPushButton(self.groupBox)
        self.btnbanco.setGeometry(QtCore.QRect(20, 20, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnbanco.setFont(font)
        self.btnbanco.setObjectName("btnbanco")
        self.btnagencia = QtWidgets.QPushButton(self.groupBox)
        self.btnagencia.setGeometry(QtCore.QRect(260, 20, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnagencia.setFont(font)
        self.btnagencia.setObjectName("btnagencia")
        self.groupBox_2 = QtWidgets.QGroupBox(frmparametros)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 140, 721, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.btnlojas = QtWidgets.QPushButton(self.groupBox_2)
        self.btnlojas.setGeometry(QtCore.QRect(380, 20, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnlojas.setFont(font)
        self.btnlojas.setObjectName("btnlojas")
        self.btncidade = QtWidgets.QPushButton(self.groupBox_2)
        self.btncidade.setGeometry(QtCore.QRect(140, 20, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btncidade.setFont(font)
        self.btncidade.setObjectName("btncidade")

        self.retranslateUi(frmparametros)
        QtCore.QMetaObject.connectSlotsByName(frmparametros)
        frmparametros.setTabOrder(self.btnbanco, self.btnagencia)
        frmparametros.setTabOrder(self.btnagencia, self.btnconta)
        frmparametros.setTabOrder(self.btnconta, self.btncidade)
        frmparametros.setTabOrder(self.btncidade, self.btnlojas)

    def retranslateUi(self, frmparametros):
        _translate = QtCore.QCoreApplication.translate
        frmparametros.setWindowTitle(_translate("frmparametros", "Seleccionar um parametro"))
        self.groupBox.setTitle(_translate("frmparametros", "Contas"))
        self.btnconta.setText(_translate("frmparametros", "Abrir Contas"))
        self.btnbanco.setText(_translate("frmparametros", "Abrir Bancos"))
        self.btnagencia.setText(_translate("frmparametros", "Abrir Agencias"))
        self.groupBox_2.setTitle(_translate("frmparametros", "Lojas"))
        self.btnlojas.setText(_translate("frmparametros", "Abrir Lojas"))
        self.btncidade.setText(_translate("frmparametros", "Abrir Cidades"))
